CakePHP 課題１
codeschoolway/quelcode-cakephp pull request #1
Opened 2020-07-01 01:45 UTC by codeschoolway

2020-07-02 10:36 UTC, piasoratech requested changes
正しく動作しない部分があるので確認をお願いします。
- カウントダウンタイマーが0になった後数値がマイナスになってしまいます。
- オークション終了後の画面でカウントダウンタイマーの表示が`日時間分秒`となってしまいます。
- 画像でないファイルをアップロードしようとしたときにエラーメッセージが`画像を選択してください。`というのはエラーメッセージとしてわかりにくいので、最低限どのようなファイルであればアップロードできるのかを記載する必要があるかと思います。
- 画像のファイル名とDBに保存されるファイルパスが異なって保存されているために画像が表示されません。

2020-07-03 06:23 UTC, Yuzunoha commented
現状 /webroot/img/auction/  が存在しないので clone しただけでは画像がアップロードできないですね><

つまりアップロードされた画像はgitで管理せず画像をアップロードする用のディレクトリはgit管理するようにしてください。

やり方は調べていただきたいのですが
/webroot/img/auction/.gitkeep という隠しファイルを作り、このファイルはgitignoreしないようにする。
/webroot/img/auction/ 配下の .gitkeep 以外のファイルはgitignoreするようにすればできます！

2020-07-03 06:29 UTC, Yuzunoha commented
>画像は拡張子がgif, jpeg, jpg または png のいずれかになります。
こちらの条件ですが、それぞれ大文字の場合(GIF, JPEG, JPG, PNG) の場合も許可してあげてください

2020-07-03 06:34 UTC, Yuzunoha commented on html/mycakeapp/src/Template/Auction/view.ctp
> +</script>
ファイルの最後で改行してください

2020-07-03 06:34 UTC, Yuzunoha commented on html/mycakeapp/.gitignore
> +/webroot/img/auction/*
ファイルの最後で改行してください

2020-07-03 08:42 UTC, Yuzunoha approved these changes
OKです！！承認しました！！！

2020-07-15 01:27 UTC, merged