CakePHP 課題２ 初回コミット
codeschoolway/quelcode-cakephp pull request #2
Opened 2020-07-15 01:53 UTC by codeschoolway

2020-07-15 11:21 UTC, yusaku-inamura requested changes
確認しました、仕様の面や実装方法について色々コメントしてありますのでご確認お願いします。
また、deliveriesテーブルに存在する更新時に時間を入れておきたいのであろうupdatedですが、発送連絡や受け取り連絡時に時間の更新が行われていないようです。
そちらも併せて確認してみてください。

実装をざっとみての感想ですが、指定したidのデータがない場合など以上系の考慮がされていて、実装上に持つべき観点としてとてもいいと思います。
方向性はとてもいいのでこのまま品質を上げていきましょう。

2020-07-15 11:21 UTC, yusaku-inamura commented on html/mycakeapp/config/Migrations/20200710100706_RemoveUpdatedAtFromRatings.php
> +    public function up()
マイグレーションファイルで `up` と `down` をそれぞれ用意し、ロールバックを用意できているのは観点としてとても良いです。
ただ、実は今回のような簡単なカラムの削除及び追加などであれば、 `change` メソッドを実装してその中にmigrationでやりたいことを書くことにより、rollback時に自動でいい感じに解釈して元に戻してくれるのです。
`change` が自動で対応してくれる範囲には限りがありますが、あまり複雑なことをやらなければ `change` だけでなんとかなることが多いです。
https://book.cakephp.org/migrations/2/ja/index.html

2020-07-15 11:21 UTC, yusaku-inamura commented on html/mycakeapp/src/Controller/AuctionController.php
> +		$user_ratings = $this->Ratings->find('all')->Where(['from_user_id'=>$user_id])->toArray();
ここは条件が違う気がしますね。
例えばuser_id=1の人のユーザーページを開いた場合、表示したいのはuser_id=1の人に対して下された評価の一覧です。
それを踏まえてもう一度条件の見直しをしてみましょう。

2020-07-15 11:21 UTC, yusaku-inamura commented on html/mycakeapp/src/Controller/AuctionController.php
> +	public function update2()
流石に関数名がよろしくないですね。
updateなのはその通りだと思うのですが、何を意味するアップデートなのかを意識してもっとわかりやすい関数名にしましょう。

2020-07-15 11:21 UTC, yusaku-inamura commented on html/mycakeapp/src/Template/Auction/add.ctp
> +		//var_dump($biditem);
デバッグ用のコードは提出時には削除するのが良いです。
基本的にコメントは意味のあるものだけ残しましょう。

2020-07-15 11:21 UTC, yusaku-inamura commented on html/mycakeapp/src/Template/Auction/contact.ctp
> +
改行が少々過剰ですね。
末尾の改行は一行だけするようにしましょう。

2020-07-15 11:21 UTC, yusaku-inamura commented on html/mycakeapp/src/Controller/AuctionController.php
> +		$user = $this->Users->findById($user_id)->toArray();
ここは `toArray` である必要があるでしょうか?
複数件取得されることを想定していないのであればあまり適切ではないですね。

2020-07-15 11:21 UTC, yusaku-inamura commented on html/mycakeapp/src/Controller/AuctionController.php
> +				$this->Flash->error(__('bbbbbbbb送信に失敗しました。もう一度入力してください。'));
ちょっとメッセージがおかしいですね。
確認用に一部変えたのかもしれませんが、確認後はちゃんと元に戻しましょう。

2020-07-15 11:21 UTC, yusaku-inamura commented on html/mycakeapp/src/Controller/AuctionController.php
> +		$bidinfo_find_bid = $this->Bidinfo->find('all')->where(['biditem_id'=>$biditem_id])->toArray();
ここは複数件取得することを想定していますか?
そうでないならtoArrayは適切ではないですね。

2020-07-15 11:21 UTC, yusaku-inamura commented on html/mycakeapp/src/Controller/AuctionController.php
> +		//
このコメントは不要そうなので消してしまいましょう。

2020-07-15 11:21 UTC, yusaku-inamura commented on html/mycakeapp/src/Template/Auction/contact.ctp
> +<?php endif; ?>
ちょっとここら辺ifが重なりすぎてどのブロックがどのifに対応するかわかりにくくなってしまっているのでインデントしっかりつけたほうが良さそうです。

2020-07-15 11:21 UTC, yusaku-inamura commented on html/mycakeapp/src/Template/Auction/home.ctp
> +		<!-- ?php $query_param = '?bid='.$info->biditem_id; ?> -->
こちらも不要ならば消しましょう。

2020-07-16 00:12 UTC, codeschoolway commented on html/mycakeapp/config/Migrations/20200710100706_RemoveUpdatedAtFromRatings.php
> +    public function up()
今回は`up`と`down`で実装しますが、今後は`change`も利用したいと思います。ありがとうございます。

2020-07-16 07:03 UTC, Yuzunoha commented on html/mycakeapp/src/Template/Auction/contact.ctp
> +        <tr><td>住所：<?= h($delivery_findby_bid[0]->address) ?></td></tr>
```suggestion
        <tr><td>住所：<?= h($delivery_findby_bid[0]->address) ?></td></tr>
```
住所の後に謎の文字があるので消してください

2020-07-16 08:23 UTC, Yuzunoha commented
修正確認しました！！OKです！！！

2020-07-16 08:23 UTC, Yuzunoha approved these changes

2020-07-29 06:55 UTC, merged